[theme]
base = "light"
primaryColor = "#0D9488"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"

[client]
toolbarMode = "minimal"

[ui]
hideTopBar = false
